/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.SQLite.JDBC;

import org.sqlite.SQLiteDataSource;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        String url = "jbc:sqlite:./fruits.db";

        SQLiteDataSource dataSource = new SQLiteDataSource();
        dataSource.setUrl(url);
        try (Connection connection = DataSource.getConnection()) {
            if (connection.isValid(5)) {
                System.out.println("Connection is valid");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
